
runtime: python310  # Usando Python 3.10

entrypoint: gunicorn -b :$PORT app:app  # Comando para iniciar o Flask com Gunicorn

env_variables:
  PIPEDRIVE_TOKEN: "592fa4db75e415cbb9e8bebbee497e3c24527f16"  # Token do Pipedrive (substitua com o seu)

instance_class: F2  # Tipo de instância do App Engine

automatic_scaling:
  min_instances: 1
  max_instances: 5

env: flex
